<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\CclDotnet.Pacman\ccl-config.yaml" Link="ccl-config.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CclDotnet.Pacman\CclDotnet.Pacman.fsproj" />
    <ProjectReference Include="..\..\tools\CatConfLang.TestRunner\CatConfLang.TestRunner.csproj" />
    <ProjectReference Include="..\..\tools\CatConfLang.TestRunner.Abstractions\CatConfLang.TestRunner.Abstractions.csproj" />
  </ItemGroup>

</Project>
